<?php

namespace ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModelMachineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelMachineRepository extends EntityRepository
{
}
